DROP  COLLECTION VORA.CAR_TELEMETRY_COLLECTION
CREATE COLLECTION VORA.CAR_TELEMETRY_COLLECTION
ALTER COLLECTION VORA.CAR_TELEMETRY_COLLECTION ADD DATASOURCE HDFS('hdfs://spark-hdfs-adapter:8020/car_telemetrydata/car_telemetry.json')
LOAD COLLECTION VORA.CAR_TELEMETRY_COLLECTION
DROP TABLE VORA.CAR_TELEMETRY_EXTRACT
CREATE  TABLE  VORA.CAR_TELEMETRY_EXTRACT ( temperature double ,battery double ,gear VARCHAR(32) ,race VARCHAR(32) , timest VARCHAR(128) ,macaddress VARCHAR(50) )  STORE IN MEMORY
ALTER TABLE VORA.CAR_TELEMETRY_EXTRACT ADD DATASOURCE HDFS('hdfs://spark-hdfs-adapter:8020/car_telemetrydata_solution/CarTelemetryStructuredDataExtract.csv')  DELIMITED BY ','
LOAD TABLE VORA.CAR_TELEMETRY_EXTRACT
CREATE TABLE VORA.CAR_PART_THRESHOLDS ( MAC VARCHAR(50) ,MAT VARCHAR(50) ,THRES DECIMAL(28,6) ,VENDNAME VARCHAR(50) ,GEW DECIMAL(28,6) ) STORE IN MEMORY TYPE DATASOURCE